name: Merge and notify
on:
  push:
    branches:
      - master
jobs:
  merge_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@master
        with:
          ref: test

      - name: Merge master
        run: |
          repository_name=$(echo ${{ env.GITHUB_REPOSITORY }} | cut -d'/' -f2)
          echo "Repository Name: $repository_name"
          
          git fetch origin
          msg="$repository_name merge into test from master success
          
          git merge origin/master || msg="$repository_name merge into test from master failed"
          git push origin test

          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
              "msg_type": "text",
              "content": {
                  "text": "'"${msg}"'"
              }
          }' \
          https://open.feishu.cn/open-apis/bot/v2/hook/f75f0d28-a103-43a6-a0dd-797b111b4498

