name: Generate PB

on:
  push:
    branches-ignore:
      - '**-go'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@master

      - name: 设置环境 Golang 环境
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: 编译pb文件并发布到新分支
        run: |
          git config --global user.name 'action'
          git config --global user.email 'action@github.com'
          
          branch_name=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          new_branch="${branch_name}-go"
          git checkout -b $new_branch
          
          echo "999">1.txt
          
          git add .
          git commit -m "Commit Message:${{ github.event.head_commit.message }}---Commit Author: ${{ github.event.head_commit.author.name }}---Make Api By Github Action"
          git push origin ${{ github.ref }}-go --force
