name: Generate PB

on:
  push:
    branches-ignore:
      - '**-go'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@master
      - name: 编译pb文件并发布到新分支
        run: |
          git config --global user.name 'action'
          git config --global user.email 'action@github.com'
          
          branch_name=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          
          echo "222">1.txt
          git add .
          git commit -m "Commit Message:${{ github.event.head_commit.message }}---Commit Author: ${{ github.event.head_commit.author.name }}---Make Api By Github Action"
          git tag v1.0.0
          git push origin --tags
