name: Merge and notify
on:
  push:
jobs:
  merge_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@master

      - name: Merge master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pr_url=$(gh pr create --base test --head master --title "Action PR" --body "Action PR")
          echo $pr_url
          
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
              "msg_type": "text",
              "content": {
                  "text": "'"${pr_url}"'"
              }
          }' \
          https://open.feishu.cn/open-apis/bot/v2/hook/f75f0d28-a103-43a6-a0dd-797b111b4498