name: Generate PB

on:
  push:
    branches-ignore:
      - '**-go'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@master

      - name: 编译pb文件并发布到新分支
        run: |
          git config --global user.name 'action'
          git config --global user.email 'action@github.com'
          
          branch_name=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          new_branch="${branch_name}-go"

          if [ "$(git ls-remote --exit-code --heads https://github.com/gopherWxf/OSS ${{ github.ref }}-go )" != "" ]; then
            git checkout "${new_branch}"
            rm -rf *
            git add .
            git commit -m "temp"
            git merge "${{ github.ref }}"
          else
            git checkout -b "${new_branch}"
          fi

          echo "666">1.txt
          
          git add .
          git commit -m "Commit Message:${{ github.event.head_commit.message }}---Commit Author: ${{ github.event.head_commit.author.name }}---Make Api By Github Action"
          git push origin ${{ github.ref }}-go