name: Merge and notify
on:
  push:
    branches:
      - master
jobs:
  merge_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@master

      - name: Merge master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pr_url=$(gh pr create --base test --head master --title "Action PR" --body "Action PR")
          echo $pr_url